//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int Equipo_ID { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
